version: '3.8'

services:
  hannie-db:
    image: postgres:16
    container_name: hanniejewelry-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: P4ssword!
      POSTGRES_USER: hanniejewelry
      POSTGRES_DB: hanniejewelry
    volumes:
      - hanniejewelry-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: hanniejewelry-redis
    ports:
      - "6379:6379"

  vault:
    image: hashicorp/vault:1.18.3
    container_name: spring_boot_vault_container
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_LOCAL_CONFIG: |
        {
          "ui": true
        }
    cap_add:
      - IPC_LOCK
    networks:
      - app_network

volumes:
  hanniejewelry-db-data:

networks:
  app_network:
