spring:
  application:
    name: demo-liquibase

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
  show-actuator: true
